# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ルートの依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      tar-updates:
        patterns:
          - "tar"

  # packages/create-next-rich-tpl の依存関係
  - package-ecosystem: "npm"
    directory: "/packages/create-next-rich-tpl"
    schedule:
      interval: "daily"
    groups:
      tar-updates:
        patterns:
          - "tar"

  # 各テンプレートの依存関係: Dependabot は各 directory エントリを個別に評価します
  - package-ecosystem: "npm"
    directory: "/templates/app/with-i18n-routing"
    schedule:
      interval: "daily"
    groups:
      tar-updates:
        patterns:
          - "tar"
      react-family:
        patterns:
          - "^react$"
          - "^react-dom$"
          - "^@types/react$"
          - "^@types/react-dom$"
      next-family:
        patterns:
          - "^next$"
          - "^eslint-config-next$"
      tailwindcss-family:
        patterns:
          - "^tailwindcss$"
          - "^@tailwindcss/postcss$"

  - package-ecosystem: "npm"
    directory: "/templates/app/without-i18n"
    schedule:
      interval: "daily"
    groups:
      tar-updates:
        patterns:
          - "tar"
      react-family:
        patterns:
          - "^react$"
          - "^react-dom$"
          - "^@types/react$"
          - "^@types/react-dom$"
      next-family:
        patterns:
          - "^next$"
          - "^eslint-config-next$"
      tailwindcss-family:
        patterns:
          - "^tailwindcss$"
          - "^@tailwindcss/postcss$"

  - package-ecosystem: "npm"
    directory: "/templates/app/without-i18n-routing"
    schedule:
      interval: "daily"
    groups:
      tar-updates:
        patterns:
          - "tar"
      react-family:
        patterns:
          - "^react$"
          - "^react-dom$"
          - "^@types/react$"
          - "^@types/react-dom$"
      next-family:
        patterns:
          - "^next$"
          - "^eslint-config-next$"
      tailwindcss-family:
        patterns:
          - "^tailwindcss$"
          - "^@tailwindcss/postcss$"
