name: Smoke tests

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'packages/create-next-rich-tpl/**'
      - '.github/workflows/smoke-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'packages/create-next-rich-tpl/**'
      - '.github/workflows/smoke-test.yml'

jobs:
  smoke-test:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Run smoke-test script
        run: |
          node scripts/smoke-test.js
